begin;
select pg_advisory_xact_lock(hashtextextended('rswtta:club-search-preregister:v1',0));
revoke all on function public.club_preregister_student_v3(text,text,text,uuid,text,text,jsonb,text,boolean) from public,anon,authenticated;
revoke all on function public.club_preview_student_preregistration_v2(text,text,text,uuid,jsonb) from public,anon,authenticated;
revoke all on function public.club_search_students(text,text,text,text) from public,anon,authenticated;
drop function public.club_preregister_student_v3(text,text,text,uuid,text,text,jsonb,text,boolean);
drop function public.club_preview_student_preregistration_v2(text,text,text,uuid,jsonb);
drop function public.club_search_students(text,text,text,text);
drop function rswtta_private.club_preregistration_preview_v2(jsonb,uuid);
drop function rswtta_private.club_search_students_snapshot(text);
drop function rswtta_private.club_preregistration_proposed_id(uuid);
drop function rswtta_private.club_preregistration_status(jsonb);
drop function rswtta_private.club_preregistration_mask_phone(text);
drop function rswtta_private.club_preregistration_mask_email(text);
drop function rswtta_private.club_preregistration_version();
drop function rswtta_private.club_preregistration_normalize_v2(jsonb);
drop index public.project_rows_unique_parent_login_alias_claim;
drop index public.project_rows_unique_parent_email_claim;
drop table rswtta_private.club_search_preregister_backup_20260914133000;
grant execute on function public.club_preregister_student_v2(text,text,text,uuid,jsonb,text) to anon,authenticated;
commit;
